name: Reusing

on:
  push:
  #workflow_dispatch: # to allow manual triggering via the UI of Github

jobs:
  regular:
    runs-on: ubuntu-latest
    name: Regular

    steps:
    - name: Regular
      run: echo Just a regular job

  run-reusable:
    uses: https://github.com/szabgab/github-actions-reusable-workflow/.github/workflows/reusable.yaml

